{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-suite-ingress
  namespace: {{ include "devops-suite.namespace" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    # Szükséges az ArgoCD és Harbor megfelelő működéséhez (pl. átirányítások kezelése)
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m" # Harbor képfeltöltésekhez
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # Jenkins elérése: devops.local/jenkins
          - path: /jenkins
            pathType: Prefix
            backend:
              service:
                name: jenkins-service
                port:
                  number: {{ .Values.jenkins.servicePort }}
          
          # Grafana elérése: devops.local/grafana
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: {{ .Values.grafana.servicePort }}

          - path: /kafka
            pathType: Prefix
            backend:
              service:
                name: kafka-service
                port:
                  number: {{ .Values.kafka.servicePort }}

{{- end }}