apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{ include "devops-suite.namespace" . }}
spec:
  serviceName: kafka-service
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            
            # A konténeren belül a 9092, 9094 és 9093-as portokon figyelünk
            - name: KAFKA_LISTENERS
              value: "INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093"
            
            # Kívülről a kliensnek azt mondjuk, hogy a 192.168.1.76:32400-as címen ér el minket
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-service:9092,EXTERNAL://192.168.1.76:32400"
            
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            
            # KRaft Controller specifikus beállítások (Ezek kellettek, hogy elinduljon!)
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
              
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kraft-combined-logs"
          ports:
            - containerPort: 9092
              name: client