apiVersion: v1
kind: Service
metadata:
  name: argocd-server-service
  namespace: {{ include "devops-suite.namespace" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.argocd.servicePort }}
      targetPort: 8080
  selector:
    app: argocd-server