apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: {{ include "devops-suite.namespace" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.grafana.servicePort }}
      targetPort: 3000
  selector:
    app: grafana