controller:initializeCommand:
  admin:
    username: "admin"             # Maradhat az alapértelmezett, vagy átírhatod
    password: "AzEnSzuperTitkosJelszavam123" # Ide írd a saját jelszavadat
    createSecret: true            # Ezzel mondod meg a Helm-nek, hogy hozzon létre belőle K8s Secret-et
additionalAgents:
  maven:
    podName: "jenkins-agent-maven"
    customJenkinsLabels: "maven-agent"
    image:
      repository: "jenkins/jnlp-agent-maven"
      tag: "latest"
  python:
    podName: "jenkins-agent-python"
    customJenkinsLabels: "python-agent"
    image:
      repository: "python"
      tag: "3.11-slim"
    command: "/bin/sh -c"
    args: "cat"
    TTYEnabled: true