controller:
  image:
    repository: "jenkins/jenkins"
    tag: "lts-jdk21"

  admin:
    username: admin
    password: heyjoe

  overwritePlugins: true
  overwritePluginsFromImage: true

  initializeOnce: false
    
  sidecars:
    configAutoReload:
      enabled: true

  containerEnv:
    - name: OVERWRITE_PLUGINS
      value: "true"

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - docker-workflow
    - job-dsl
    - pipeline-stage-view
    - blueocean
    - matrix-auth

  JCasC:
    enabled: true
    defaultConfig: false

    configScripts:
      security: |
        jenkins:
          crumbIssuer:
            standard: {}
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: admin
                  password: heyjoe

          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false

      clouds: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
                containerCapStr: "10"
                retentionTimeout: 10
                templates:
                  - name: "node-agent"
                    label: "node-agent"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                      - name: "node"
                        image: "node:20-alpine"
                        workingDir: "/home/jenkins/agent"
                        command: "cat"
                        ttyEnabled: true
                  - name: "git-agent"
                    label: "git-agent"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                      - name: "git"
                        image: "alpine/git:latest"
                        workingDir: "/home/jenkins/agent"
                        command: "cat"
                        ttyEnabled: true
                  - name: "custom-base-agent"
                    label: "custom-base-agent"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                      - name: "base"
                        image: "kmarton20002/jenkins-base-agent:latest"
                        workingDir: "/home/jenkins/agent"
                        command: "cat"
                        ttyEnabled: true
                  - name: "custom-node-builder"
                    label: "custom-node-builder"
                    nodeUsageMode: "EXCLUSIVE"
                    volumes:
                      - hostPathVolume:
                          hostPath: "/var/run/docker.sock"
                          mountPath: "/var/run/docker.sock"
                    containers:
                      - name: "node-builder"
                        image: "kmarton20002/jenkins-node-builder:latest"
                        workingDir: "/home/jenkins/agent"
                        command: "cat"
                        ttyEnabled: true
                        privileged: true
                  - name: "custom-ansible-agent"
                    label: "custom-ansible-agent"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                      - name: "ansible"
                        image: "kmarton20002/jenkins-ansible-agent:latest"
                        workingDir: "/home/jenkins/agent"
                        command: "cat"
                        ttyEnabled: true
                  - name: "custom-buildx-agent"
                    label: "custom-buildx-agent"
                    nodeUsageMode: "EXCLUSIVE"
                    volumes:
                      - hostPathVolume:
                          hostPath: "/var/run/docker.sock"
                          mountPath: "/var/run/docker.sock"
                    containers:
                      - name: "buildx"
                        image: "kmarton20002/jenkins-buildx-agent:latest"
                        workingDir: "/home/jenkins/agent"
                        command: "cat"
                        ttyEnabled: true
                        privileged: true
                        runAsUser: 0

rbac:
  create: true

serviceAccount:
  create: true
  name: jenkins